### PR TITLE
Random internal server error debug

### PR DESCRIPTION
**Pull request by tarreislam**

### CODE REVIEW

**Comment by driesvints** [comment]
Please add a thorough description why this is needed as well as a way to reproduce this.

**Comment by tarreislam** [comment]
I've tried to be thorough by providing screenshots and code examples but ill try again.

Reverb is not stable and its impossible to know why because the internal server error is gatekept.

**How to reproduce**

1. create a small array payload `range(0,1024)`
2. broadcast it in an event with `ShouldBroadcastNow` in a while loop
4. See how https://github.com/laravel/reverb/blob/main/src/Protocols/Pusher/Http/Controllers/EventsController.php#L28 fails because the entire payload is not there

**Comment by taylorotwell** [comment]
Drafting pending review from @joedixon

**Comment by joedixon** [comment]
Closing in favour of #128

**Comment by joedixon** [comment]
Closing in favour of #128

**Comment by tarreislam** [comment]
> Closing in favour of #128

Thank you!

**Pull request closed without merging**
