### PR TITLE
Fix: Update Signal Handling for Unix-like and added Windows Systems support

### PR DESCRIPTION
**Pull request by yourchocomate**
https://github.com/laravel/reverb/assets/81873266/6c7e2451-2320-4a89-863f-ad7e59994fdd

Fix: #65 
Fix: #74

**Description**
This PR enhances the signal handling mechanism to support both Unix-like systems and Windows. It introduces support for SIGTSTP on Unix-like systems and implements Windows-specific signal handling using sapi_windows_set_ctrl_handler. This update improves the platform compatibility of the application and ensures proper signal handling across different operating systems

**Changes Made**

- Added SIGTSTP to the list of subscribed signals for Unix-like systems to not suspend process without gracefullyDisconnect the opened server
- Introduced a new method `handleSignalWindows() `to handle signals on Windows.
- Implemented Windows-specific signal handling using `sapi_windows_set_ctrl_handler`.

**Testing**

- Tested on Unix-like systems to ensure correct handling of SIGTSTP.
- Tested on Windows to verify proper signal handling using sapi_windows_set_ctrl_handler.

**Any feedback or suggestions for improvement are welcome.**

### CODE REVIEW

**Comment by luisprmat** [comment]
image

This is the issue in windows that this PR solves.
It worked for me, but making that modification.

**Comment by mfrizky** [comment]
I still get the same error in docker environment with php 8.3.4 fpm-bookworm in my development server. This problem doesnt occure to me on my local machine with windows OS non docker environment.

**Comment by yourchocomate** [comment]
> I still get the same error in docker environment with php 8.3.4 fpm-bookworm in my development server. This problem doesnt occure to me on my local machine with windows OS non docker environment.

I will check it out, Can you provide the docker config you have used?

**Comment by mfrizky** [comment]
> > I still get the same error in docker environment with php 8.3.4 fpm-bookworm in my development server. This problem doesnt occure to me on my local machine with windows OS non docker environment.
> 
> I will check it out, Can you provide the docker config you have used?

Sure, here are my docker-compose.yml
`
version: '3.8'

services:
  app:
    container_name: ticketing-dev
    build: 
      context: ./php
      dockerfile: Dockerfile
    networks:
      - cl-network
    ports:
      - "9002:9000"
    volumes:
      - ./src:/var/www/ticketing-backend
    working_dir: /var/www/ticketing-backend

networks:
  cl-network:
    name: cl-network
    external: true
`

And for Dockerfile is this :
`
FROM php:8.3.4-fpm-bookworm

# Install composer
RUN echo "\e[1;33mInstall COMPOSER\e[0m"
RUN cd /tmp \
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

RUN apt-get update

# Install useful tools
RUN apt-get -y install apt-utils nano wget dialog vim

# Install important libraries
RUN echo "\e[1;33mInstall important libraries\e[0m"
RUN apt-get -y install --fix-missing \
        apt-utils \
        build-essential \
        git \
        curl \
        libcurl4 \
        libcurl4-openssl-dev \
        supervisor \
        zlib1g-dev \
        libzip-dev \
        zip \
        libbz2-dev \
        locales \
        libmcrypt-dev \
        libicu-dev \
        libonig-dev \
        libxml2-dev \
    && pecl install redis \
    && docker-php-ext-enable redis
    
# RUN echo "\e[1;33mInstall important docker dependencies\e[0m"
# RUN docker-php-ext-install \
#     exif \
#     pcntl \
#     bcmath \
#     ctype \
#     curl \
#     iconv \
#     xml \
#     soap \
#     pcntl \
#     mbstring \
#     tokenizer \
#     bz2 \
#     zip \
#     intl

# Install Postgre PDO
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql sockets

RUN  mkdir -p /var/www/ticketing-backend
RUN chown -R www-data:www-data /var/www/ticketing-backend
#WORKDIR /var/www/html
#RUN composer install
#RUN composer require league/flysystem-aws-s3-v3 "^3.0"
COPY supervisord.conf /etc/supervisord.conf
COPY www.conf /usr/local/etc/php-fpm.d/www.conf
ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
`

**Comment by mfrizky** [comment]
Sure, here are my docker-compose-yml and Dockerfile of my php :
[Dockerfile.txt](https://github.com/laravel/reverb/files/14784302/Dockerfile.txt)
[docker compose yml.txt](https://github.com/laravel/reverb/files/14784303/docker.compose.yml.txt)

**Pull request merged**
