### PR TITLE
[1.x] Allows for disconnections when broadcasting to others

### LINKED ISSUE #121: Broadcast message toOthers throws ApiException in pusher
### Reverb Version

1.0.0-beta4

### Laravel Version

11.1.0

### PHP Version

8.3.4

### Description

When i try to send broadcast message via my Event like this
`broadcast(new MyEvent())->toOthers()`
I receive an Exception
```
[2024-03-28 16:26:08] local.ERROR: Pusher error: Internal server error.. {"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Pusher error: Internal server error.. at /home/ss/workspace/chat/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:164)
[stacktrace]
#0 /home/ss/workspace/chat/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(92): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast()
```
In laravel-websockets, which i used before, same method work without errors.

### Steps To Reproduce

`broadcast(new MyEvent())->toOthers()`
receive exception
```
[2024-03-28 16:26:08] local.ERROR: Pusher error: Internal server error.. {"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Pusher error: Internal server error.. at /home/ss/workspace/chat/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:164)
[stacktrace]
#0 /home/ss/workspace/chat/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(92): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast()
```
When i add in Reverb inside handleRequest method of Laravel\Reverb\Servers\Reverb\Http\Server
`            $this->close($connection, 500, $e->getMessage());
`

instead of
`            $this->close($connection, 500, 'Internal server error.');
`
Which a give ZERO info about what happening inside this error
I receive some more info
```
message
: 
"Pusher error: Undefined array key \"875833828.561499442\"."
```
Maybe problem in line
`            isset($payload['socket_id']) ? $this->channels->connections()[$payload['socket_id']]->connection() : null
`
But didn't understand what is wrong. When remove ->toOthers() - all work good
Thank you

### PR DESCRIPTION
**Pull request by cryptoprof**
Probably will fix issue with the Exception when use toOthers()

Resolves #121

### CODE REVIEW

**Comment by taylorotwell** [comment]
Probably? 😅

**Comment by cryptoprof** [comment]
> Probably? 😅

After several years of programming, I often find that code has two quantum states - it works perfectly on the developer's computer, but on the tester's and user's computers, it may or may not work =) When I'm editing someone else's code, especially that of people smarter than me, it often turns out to be not a bug, but a feature.

**Comment by joedixon** [comment]
This PR does indeed protect against a potential issue when using `toOthers` in the event the connection you wish to ignore has disconnected before the event has been broadcasted.

I have updated the formatting a little and introduced a test.

**Comment by RTippin** [comment]
I can confirm that all of the intermittent `Pusher 500` errors I have been observing occur when using `toOthers` and the client has already left the channel / refreshed entire screen.

**Pull request merged**
